"""adding column gender

Revision ID: 8e0e43b1d275
Revises: 97379b656130
Create Date: 2025-08-03 11:55:45.924997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic import op
import sqlalchemy as sa

def upgrade():
    # Step 1: Add the column as nullable first
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))

    # Step 2: Set default value for existing rows
    op.execute("UPDATE users SET gender = 'Not specified' WHERE gender IS NULL")

    # Step 3: Make the column non-nullable
    op.alter_column('users', 'gender', nullable=False)

def downgrade():
    op.drop_column('users', 'gender')



# revision identifiers, used by Alembic.
revision: str = '8e0e43b1d275'
down_revision: Union[str, Sequence[str], None] = '97379b656130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
