"""add user

Revision ID: b37aeff99c44
Revises: 86be842bcc8d
Create Date: 2025-08-03 11:46:04.642688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37aeff99c44'
down_revision: Union[str, Sequence[str], None] = '86be842bcc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
